name:                misskey-rss-bot
version:             0.0.1.0
github:              githubuser/misskey-rss-bot
license:             GPL3
author:              Sam Smucny
maintainer:          
copyright:           2023 Sam Smucny

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/ssmucny/misskey-rss-bot#readme>

dependencies:
- base >= 4.11 && < 10
- rio >= 0.1.12.0
- yaml
- text
- bytestring
- http-client
- http-conduit
- http-types
- http-client-tls
- feed
- aeson
- async
- containers
- time

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  misskey-rss-bot-exe:
    main:                Main.hs
    source-dirs:         app
    dependencies:
    - misskey-rss-bot
    - optparse-simple

    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

tests:
  misskey-rss-bot-test:
    main:                Spec.hs
    source-dirs:         test
    dependencies:
    - misskey-rss-bot
    - hspec

    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

default-extensions:
  - NoImplicitPrelude
  - OverloadedStrings
  - DuplicateRecordFields
  - OverloadedRecordDot
  - BangPatterns